changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
  categories:
    - title: Bug Fixes 🛠
      labels:
        - Semver-Major
        - bug
    - title: Exciting New Features 🎉
      labels:
        - enhancement
    - title: Documentation ?!?!
      labels:
        - documentation    
    - title: Other Changes
      labels:
        - "*"